//! Time-domain granular pitch shifter (SOLA-style, no FFT).
//!
//! Uses a sliding **grain-and-overlap** scheme that decouples the
//! playback rate (which controls pitch) from the time progression
//! (which we want to keep at 1.0× so the audio doesn't speed up or
//! slow down).
//!
//! # Topology
//!
//! Per channel we keep a sliding **input buffer** that the caller
//! writes into. The output is generated by reading **resampled**
//! grains from this buffer at a non-unit playback rate `r =
//! 2^(semitones/12)`, then cross-fading them with a Hann window so
//! grain boundaries don't click.
//!
//! ```text
//! grain_size = 2048 samples (≈ 43 ms @ 48 kHz)
//! hop_out    = grain_size / 2     ─ output advances 1024 samples per grain
//! ```
//!
//! Each output grain is built by linearly resampling the input
//! window `[read_pos, read_pos + grain_size · r)` to `grain_size`
//! samples — that resampling is what produces the pitch shift.
//! After emitting `hop_out` cross-faded samples we advance `read_pos`
//! by `hop_out` (keeping output time at 1.0× input time on average).
//!
//! For semitones = 0 (`r = 1`) the resampling is the identity, so
//! the cross-fade reproduces the input.
//!
//! For semitones > 0 (`r > 1`) the resampling consumes more input
//! per grain, pitching the grain up.
//!
//! For semitones < 0 (`r < 1`) the resampling consumes less input
//! per grain, pitching the grain down.
//!
//! # Latency / buffering
//!
//! Output is delayed by ~1 grain (2048 samples ≈ 43 ms) to give
//! the pitch shifter enough lookahead. We accumulate input until
//! the buffer has at least `grain_size + 1` samples, then start
//! emitting cross-faded grains.

use crate::sample_convert::{decode_to_f32, encode_from_f32};
use crate::{AudioFilter, AudioStreamParams};
use oxideav_core::{AudioFrame, Result};

/// Grain length in samples (must be even). 2048 ≈ 43 ms @ 48 kHz.
const GRAIN_SIZE: usize = 2048;
/// Hop between successive output grains. Half-grain ⇒ 50 % overlap.
const HOP_OUT: usize = GRAIN_SIZE / 2;

/// Per-channel state.
#[derive(Debug, Clone)]
struct ChState {
    /// Sliding input buffer (grows as samples arrive, drained from
    /// the front when older than the read pointer needs).
    input: Vec<f32>,
    /// Fractional read pointer (samples into `input`).
    read_pos: f64,
    /// Hann window of length `GRAIN_SIZE`.
    window: Vec<f32>,
    /// Pre-built half-grain accumulator for the previous tail's
    /// cross-fade. Length `HOP_OUT`.
    overlap: Vec<f32>,
    /// Number of valid samples in `overlap`. 0 before the first
    /// grain has been emitted.
    overlap_filled: usize,
}

impl ChState {
    fn new() -> Self {
        let mut window = vec![0.0f32; GRAIN_SIZE];
        // Hann window: w[n] = 0.5 · (1 - cos(2π n / (N-1)))
        let denom = (GRAIN_SIZE - 1) as f32;
        for (n, w) in window.iter_mut().enumerate() {
            *w = 0.5 * (1.0 - (2.0 * std::f32::consts::PI * (n as f32) / denom).cos());
        }
        Self {
            input: Vec::with_capacity(GRAIN_SIZE * 4),
            read_pos: 0.0,
            window,
            overlap: vec![0.0; HOP_OUT],
            overlap_filled: 0,
        }
    }

    /// Linear interpolation of the input buffer at fractional index
    /// `idx`. Returns 0 outside the buffer.
    fn sample(&self, idx: f64) -> f32 {
        if idx < 0.0 {
            return 0.0;
        }
        let i0 = idx.floor() as isize;
        let frac = (idx - i0 as f64) as f32;
        let n = self.input.len() as isize;
        if i0 < 0 || i0 + 1 >= n {
            return 0.0;
        }
        let a = self.input[i0 as usize];
        let b = self.input[(i0 + 1) as usize];
        a * (1.0 - frac) + b * frac
    }
}

/// Time-domain pitch shifter (`-12..=+12` semitones).
#[derive(Debug, Clone)]
pub struct PitchShift {
    semitones: f32,
    state: Vec<ChState>,
}

impl PitchShift {
    /// New pitch shifter. `semitones` is clamped to `[-12, +12]`;
    /// non-finite values fall back to `0` (no shift). NaN MUST be
    /// scrubbed here: it would make `ratio()` NaN, and the grain loop's
    /// have-enough-input comparison (`NaN >= len` is false) would then
    /// never stop emitting — an unbounded-memory hang, not just bad
    /// audio.
    pub fn new(semitones: f32) -> Self {
        Self {
            semitones: crate::clamp_param(semitones, 0.0, -12.0, 12.0),
            state: Vec::new(),
        }
    }

    /// Currently-configured semitone offset.
    pub fn semitones(&self) -> f32 {
        self.semitones
    }

    fn ensure_state(&mut self, channels: usize) {
        if self.state.len() != channels {
            self.state = (0..channels).map(|_| ChState::new()).collect();
        }
    }

    /// Pitch-shift ratio (`r = 2^(semitones/12)`).
    fn ratio(&self) -> f64 {
        2.0_f64.powf((self.semitones as f64) / 12.0)
    }

    /// Produce all pending output samples for one channel given the
    /// current `input` buffer state. Returns the new outputs to
    /// append to the caller's emit-buffer.
    fn process_channel(&self, st: &mut ChState, ratio: f64) -> Vec<f32> {
        let mut out = Vec::new();
        // Each output grain reads from `[read_pos, read_pos + grain_size·r)`
        // by **resampling** to `GRAIN_SIZE` output samples — that
        // resampling is what produces the pitch shift.
        loop {
            // Need read_pos + GRAIN_SIZE·ratio worth of input to build
            // the grain.
            let grain_input_end = st.read_pos + (GRAIN_SIZE as f64) * ratio;
            // Defence in depth: a non-finite ratio / read_pos would
            // make the comparison below permanently false and this
            // loop would emit output forever. The constructor scrubs
            // `semitones`, but never trust a recursive f64 cursor.
            if !grain_input_end.is_finite() {
                break;
            }
            // Add 2 samples of safety for the linear interpolator.
            if grain_input_end + 2.0 >= st.input.len() as f64 {
                break;
            }
            // Build one resampled-and-windowed grain.
            let mut grain = vec![0.0f32; GRAIN_SIZE];
            for (n, sample) in grain.iter_mut().enumerate() {
                let idx = st.read_pos + (n as f64) * ratio;
                *sample = st.sample(idx) * st.window[n];
            }
            // Emit first half: window + overlap with previous tail.
            for (n, &g) in grain.iter().enumerate().take(HOP_OUT) {
                let v = if st.overlap_filled > 0 {
                    g + st.overlap[n]
                } else {
                    g
                };
                out.push(v);
            }
            // Save second half into `overlap` for next iteration's
            // cross-fade.
            st.overlap[..HOP_OUT].copy_from_slice(&grain[HOP_OUT..(HOP_OUT + HOP_OUT)]);
            st.overlap_filled = HOP_OUT;
            // Advance read pointer by HOP_OUT — output time runs at
            // 1.0× input time. The pitch shift came from the
            // intra-grain resampling above.
            st.read_pos += HOP_OUT as f64;
        }
        // Trim the front of `input` if read_pos has moved well past
        // the start (keep a one-grain-wide history for safety).
        let drop_n = st.read_pos.floor() as i64;
        if drop_n > GRAIN_SIZE as i64 {
            let drop_amount = (drop_n - GRAIN_SIZE as i64) as usize;
            if drop_amount <= st.input.len() {
                st.input.drain(..drop_amount);
                st.read_pos -= drop_amount as f64;
            }
        }
        out
    }

    /// Reset internal buffers.
    pub fn reset(&mut self) {
        for st in self.state.iter_mut() {
            st.input.clear();
            st.read_pos = 0.0;
            for v in st.overlap.iter_mut() {
                *v = 0.0;
            }
            st.overlap_filled = 0;
        }
    }
}

impl AudioFilter for PitchShift {
    fn process(
        &mut self,
        input: &AudioFrame,
        params: AudioStreamParams,
    ) -> Result<Vec<AudioFrame>> {
        let channels = decode_to_f32(input, params.format, params.channels)?;
        let n_chan = channels.len();
        self.ensure_state(n_chan);
        let ratio = self.ratio();

        let mut out_channels: Vec<Vec<f32>> = Vec::with_capacity(n_chan);
        // Produce per-channel outputs and find the shortest length
        // (so the multi-channel output has consistent shape).
        let mut min_len = usize::MAX;
        let mut per_ch: Vec<Vec<f32>> = Vec::with_capacity(n_chan);
        for (ch_idx, ch_in) in channels.iter().enumerate().take(n_chan) {
            self.state[ch_idx].input.extend_from_slice(ch_in);
            let produced = self.process_channel_static(ch_idx, ratio);
            min_len = min_len.min(produced.len());
            per_ch.push(produced);
        }
        if min_len == usize::MAX {
            min_len = 0;
        }
        // Truncate each channel to min_len so the output frame is
        // rectangular. process_channel always emits in HOP_OUT-sized
        // blocks per pass and channels are driven from the same
        // input length, so they normally produce the same number of
        // output samples in lock-step. The min_len step is defence
        // against rounding.
        for buf in per_ch.iter_mut() {
            buf.truncate(min_len);
            out_channels.push(std::mem::take(buf));
        }

        if min_len == 0 {
            // Not enough input yet to emit a grain. Return empty.
            return Ok(Vec::new());
        }

        let out = encode_from_f32(params.format, params.channels, input, &out_channels)?;
        Ok(vec![out])
    }
}

impl PitchShift {
    /// Indirection to keep `process_channel` borrow-clean — `self`
    /// is borrowed mutably for state, but `process_channel` only
    /// needs `&self` for `ratio()` etc. Splitting makes the borrow
    /// checker happy.
    fn process_channel_static(&mut self, ch_idx: usize, ratio: f64) -> Vec<f32> {
        // Take the state out, process it, put it back. This avoids
        // borrowing `self` and `self.state[ch_idx]` simultaneously.
        let mut st = std::mem::replace(&mut self.state[ch_idx], ChState::new());
        let out = self.process_channel(&mut st, ratio);
        self.state[ch_idx] = st;
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxideav_core::SampleFormat;

    fn f32_mono(rate: u32) -> AudioStreamParams {
        AudioStreamParams {
            format: SampleFormat::F32,
            channels: 1,
            sample_rate: rate,
        }
    }

    fn make_f32_mono(samples: &[f32]) -> AudioFrame {
        let mut bytes = Vec::with_capacity(samples.len() * 4);
        for s in samples {
            bytes.extend_from_slice(&s.to_le_bytes());
        }
        AudioFrame {
            samples: samples.len() as u32,
            pts: None,
            data: vec![bytes],
        }
    }

    fn read_f32(frame: &AudioFrame) -> Vec<f32> {
        frame.data[0]
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect()
    }

    /// Count zero-crossings of a signal — a quick proxy for fundamental
    /// frequency on a clean sine.
    fn zero_crossings(x: &[f32]) -> usize {
        let mut n = 0;
        for w in x.windows(2) {
            if (w[0] >= 0.0) != (w[1] >= 0.0) {
                n += 1;
            }
        }
        n
    }

    fn sine(freq: f32, fs: u32, n: usize) -> Vec<f32> {
        let w = 2.0 * std::f32::consts::PI * freq / fs as f32;
        (0..n).map(|i| (i as f32 * w).sin() * 0.5).collect()
    }

    #[test]
    fn shift_zero_passes_signal_through() {
        // Push a long sine through with semitones=0; the output (after
        // grain warm-up) should reproduce the input shape — not
        // necessarily bit-exact (Hann cross-fade introduces tiny
        // numerical noise), but RMS should be roughly preserved.
        let fs = 48_000u32;
        let in_samples = sine(440.0, fs, fs as usize); // 1 second
        let frame = make_f32_mono(&in_samples);
        let mut p = PitchShift::new(0.0);
        let out = p.process(&frame, f32_mono(fs)).unwrap();
        assert!(!out.is_empty(), "no output produced");
        let got = read_f32(&out[0]);
        // Skip the first two grains of warm-up.
        let warm = GRAIN_SIZE * 2;
        if got.len() <= warm {
            return;
        }
        let in_rms = {
            let s: f64 = in_samples[warm..]
                .iter()
                .map(|&v| (v as f64) * (v as f64))
                .sum();
            (s / (in_samples.len() - warm) as f64).sqrt()
        };
        let out_rms = {
            let s: f64 = got[warm..].iter().map(|&v| (v as f64) * (v as f64)).sum();
            (s / (got.len() - warm) as f64).sqrt()
        };
        assert!(
            (out_rms / in_rms - 1.0).abs() < 0.1,
            "RMS ratio {} (expected ≈ 1.0)",
            out_rms / in_rms
        );
    }

    #[test]
    fn shift_octave_up_doubles_zero_crossing_rate() {
        let fs = 48_000u32;
        let f0 = 220.0f32; // input fundamental
        let in_samples = sine(f0, fs, 2 * fs as usize); // 2 seconds
        let frame = make_f32_mono(&in_samples);
        let mut p = PitchShift::new(12.0);
        let out = p.process(&frame, f32_mono(fs)).unwrap();
        assert!(!out.is_empty(), "no output produced");
        let got = read_f32(&out[0]);

        // Reference zero-crossing count for input f0 over the same
        // window we will analyse from the output.
        // Need a clean window past warm-up.
        let warm = GRAIN_SIZE * 4;
        let analyse_n = (fs as usize) / 2; // 0.5 seconds
        if got.len() < warm + analyse_n {
            panic!(
                "output too short: got.len()={} need={}",
                got.len(),
                warm + analyse_n
            );
        }
        let zc_in = zero_crossings(&in_samples[warm..warm + analyse_n]);
        let zc_out = zero_crossings(&got[warm..warm + analyse_n]);
        // Octave shift → 2× the zero-crossing rate; allow ±20 %.
        let ratio = zc_out as f32 / zc_in as f32;
        assert!(
            (ratio - 2.0).abs() < 0.4,
            "octave-up ratio {} (expected ≈ 2.0): zc_in={}, zc_out={}",
            ratio,
            zc_in,
            zc_out
        );
    }

    #[test]
    fn shift_clamped_to_octave_range() {
        let p = PitchShift::new(50.0);
        assert_eq!(p.semitones(), 12.0);
        let p = PitchShift::new(-50.0);
        assert_eq!(p.semitones(), -12.0);
    }

    #[test]
    fn first_call_may_buffer_silently_until_grain_ready() {
        // A short burst (under one grain) must not panic and should
        // either return empty or partial output. Verifying robustness
        // against undersized input frames.
        let frame = make_f32_mono(&[0.5f32; 100]);
        let mut p = PitchShift::new(2.0);
        let _ = p.process(&frame, f32_mono(48_000)).unwrap();
        // No panic ⇒ pass.
    }
}
